name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop -l
          bundle exec rspec
